### ISSUE TITLE
Show desktop notification about ending the task

### ISSUE THREAD

**Issue by anki-code** [astronouth7303/xontrib-schedule#6]
subj

Example: desktop notifications in [xontrib-cmd-durations](https://github.com/jnoortheen/xontrib-cmd-durations#usage)

**Comment by AstraLuma** [comment]
Nope, out of scope for this xontrib. I suggest rolling it into your jobs or making a wrapper of some kind.

Plus, cross-platform notifications is pretty annoying and not something I want to maintain.
